version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: foo
      TZ: Asia/Tokyo
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./mysql-confd/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-confd/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: foo
    links:
    - db
    ports:
    - 18080:80
